### ISSUE TITLE
Ubuntu build failure: 'pystache' python module not found

### ISSUE THREAD

**Issue by liviu-rolo** [BelledonneCommunications/linphone-sdk#179]
Relevant Dockerfile code:
```
FROM debian:buster-slim as builder

WORKDIR /usr/local/src

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apt apt-utils procps \
    build-essential \
    cmake doxygen ninja-build pkg-config python3 python3-pip \
    # python-pystache python-six \
    && pip3 install setuptools==58 wheel \
    && pip3 install pystache six \
    ;
```
(I copy the code since `git clone https://github.com/BelledonneCommunications/linphone-sdk.git --recursive` takes so much time).

I am following the build indications:
```
mkdir build && cd build
cmake ..
```
Error:
```
-- Setting build type to 'RelWithDebInfo' as none was specified
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.3", minimum required is "3") 
CMake Error at cmake/LinphoneSdkUtils.cmake:249 (message):
  'pystache' python module not found
Call Stack (most recent call first):
  cmake/LinphoneSdkCheckBuildToolsCommon.cmake:29 (linphone_sdk_check_python_module_is_installed)
  cmake/LinphoneSdkCheckBuildToolsDesktop.cmake:24 (include)
  cmake/LinphoneSdkPlatformDesktop.cmake:24 (include)
  CMakeLists.txt:86 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/liblinphone/build/CMakeFiles/CMakeOutput.log".
```

Further
```
# pip3 list
Package    Version
---------- -------
pip        18.1   
pystache   0.5.4  
setuptools 58.0.0 
six        1.16.0 
wheel      0.37.0 
```

```
# python3 -c "import pystache"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pystache/__init__.py", line 9, in <module>
    from pystache.init import parse, render, Renderer, TemplateSpec
  File "/usr/local/lib/python3.7/dist-packages/pystache/init.py", line 8, in <module>
    from pystache.parser import parse
  File "/usr/local/lib/python3.7/dist-packages/pystache/parser.py", line 15
    NON_BLANK_RE = re.compile(ur'^(.)', re.M)
                                     ^
SyntaxError: invalid syntax
```

**Comment by liviu-rolo** [comment]
A hacky solution: Ubuntu 18.04 + Python 3.5 (binary found somewhere) + cmake 3.15.7 (built)

Better solutions:
* use a Docker image with pre-built binaries (macOS ?)
* Mustache seems to be used only for Java, Swift, C#: just ignore it for C/C++!
* patch pystache for the latest Python 3 version

**Comment by liviu-rolo** [comment]
Pystache seems to work in the following image:
