### ISSUE TITLE
[Bug]: CMakeFiles/EP_openh264.dir/all] Error 2

### ISSUE THREAD

**Issue by pergolafabio** [BelledonneCommunications/linphone-sdk#236]
### Context

Hi, trying to build a linphone on my debian 11 system, but if fails when i enable openh264 , and i want h264 support in my linphonec terminal... what am i missing?

### General information

- Device: LinphoneC terminal purposes
- OS: Building on Debian 11
- Version of the App: 5.1
- Version of the SDK:  5.1 ?

### Expected behaviour

Compile h264 without error

### To Reproduce

```
git clone --branch release/5.1 https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
cmake -DENABLE_NON_FREE_CODECS=1 -DENABLE_OPENH264=1 -DENABLE_EMBEDDED_OPENH264=1 -DENABLE_JPEG:BOOL=OFF -DENABLE_SOUND=OFF -DENABLE_FFMPEG=ON 
```

### Additional context

```
Scanning dependencies of target EP_openh264
[ 82%] Creating directories for 'EP_openh264'
[ 83%] No download step for 'EP_openh264'
[ 83%] No update step for 'EP_openh264'
[ 83%] No patch step for 'EP_openh264'
[ 84%] Performing configure step for 'EP_openh264'
[ 84%] Forcing build for 'EP_openh264'
[ 84%] Performing build step for 'EP_openh264'
Traceback (most recent call last):
  File "/usr/local/bin/nasm", line 5, in <module>
    from nasm.console import main
  File "/usr/local/lib/python3.9/dist-packages/nasm/console.py", line 15
    print res
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(res)?
make[6]: *** [../../../..//external/openh264/codec/common/targets.mk:101: codec/common/x86/cpuid.o] Error 1
make[5]: *** [CMakeFiles/EP_openh264.dir/build.make:133: /app/linphone-sdk/WORK/desktop/Stamp/EP_openh264/EP_openh264-build] Error 2
make[4]: *** [CMakeFiles/Makefile2:832: CMakeFiles/EP_openh264.dir/all] Error 2
make[3]: *** [Makefile:103: all] Error 2
make[2]: *** [CMakeFiles/sdk.dir/build.make:133: sdk-prefix/src/sdk-stamp/sdk-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/sdk.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by KyronNextLevel** [comment]
Hello. It seems like a python 2/3 issue (your python 3 doesn't understand python 2 code). I don't have time to investigate further but maybe this could help you.

Regards,

**Comment by pergolafabio** [comment]
np, thnx for feedback
