### ISSUE TITLE
Android 4.4   arr Error

### ISSUE THREAD

**Issue by adminmastor** [BelledonneCommunications/linphone-sdk#56]
09-14 14:14:26.626 10004-10004/com.dnake.desktop E/dalvikvm: dlopen("/data/app-lib/com.dnake.desktop-2/libbctoolbox.so") failed: dlopen failed: cannot locate symbol "__read_chk" referenced by "libbctoolbox.so"...
09-14 14:14:26.626 10004-10004/com.dnake.desktop E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dnake.desktop, PID: 10004
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__read_chk" referenced by "libbctoolbox.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at org.linphone.core.FactoryImpl.<clinit>(Factory.java:534)
        at org.linphone.core.Factory.instance(Factory.java:47)
        at com.dnake.utils.LinphoneContext.<init>(LinphoneContext.java:84)
        at com.dnake.desktop.SysService.onCreate(SysService.java:53)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
        at android.app.ActivityThread.access$1800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
09-14 14:14:26.956 580-647/system_process E/InputDispatcher: channel '41e17328 com.dnake.desktop/com.dnake.desktop.PhoneMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by Viish** [comment]
Hi,
What version of the SDK are you using? What NDK did you use to build it?
Cheers,

**Comment by adminmastor** [comment]
Android-Sdk 28    NDK 21

**Comment by adminmastor** [comment]
> Hi,
> What version of the SDK are you using? What NDK did you use to build it?
> Cheers,
Android-Sdk 28 NDK 21  It's compiled ARR Running on Android 4.4  report errors
9-14 15:26:00.676 323-323/com.dnake.desktop E/dalvikvm: dlopen("/data/app-lib/com.dnake.desktop-1/libbctoolbox.so") failed: dlopen failed: cannot locate symbol "__read_chk" referenced by "libbctoolbox.so"...
09-14 15:26:00.676 323-323/com.dnake.desktop E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dnake.desktop, PID: 323
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__read_chk" referenced by "libbctoolbox.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at org.linphone.core.FactoryImpl.<clinit>(Factory.java:534)
        at org.linphone.core.Factory.instance(Factory.java:47)
        at com.dnake.utils.LinphoneContext.<init>(LinphoneContext.java:84)
        at com.dnake.desktop.SysService.onCreate(SysService.java:53)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
        at android.app.ActivityThread.access$1800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Viish** [comment]
That's why. To be able to build an AAR for 4.4 you must use NDK 17c or older.
Also note you can't build our SDK version 4.5.0-alpha which is only compatible to Android 6 or newer, you must stay on release 4.4.

**Comment by adminmastor** [comment]
HI
If I want to run linphone on Android 4.4, how to build it?

**Comment by adminmastor** [comment]
liphone release 4.4 How to build？
