### ISSUE TITLE
AAR artefact group is: org.linphone, SDK version 4.4.0

### ISSUE THREAD

**Issue by adminmastor** [BelledonneCommunications/linphone-sdk#59]
Hi!
I used the source code of 4.4 to compile ARR, and it reported an error when running on Android 4.4
 NDK VERSION21   SDK VERSION 28      Code branch  git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive -b 4.4.0
ERROR 
09-15 09:54:57.836 12637-12637/com.dnake.desktop E/dalvikvm: dlopen("/data/app-lib/com.dnake.desktop-1/libbctoolbox.so") failed: dlopen failed: cannot locate symbol "__strncpy_chk2" referenced by "libbctoolbox.so"...
09-15 09:54:57.836 12637-12637/com.dnake.desktop E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dnake.desktop, PID: 12637
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__strncpy_chk2" referenced by "libbctoolbox.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at org.linphone.core.FactoryImpl.<clinit>(Factory.java:476)
        at org.linphone.core.Factory.instance(Factory.java:46)
        at com.dnake.utils.LinphoneContext.<init>(LinphoneContext.java:84)
        at com.dnake.desktop.SysService.onCreate(SysService.java:53)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
        at android.app.ActivityThread.access$1800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Viish** [comment]
I already told you you need to build using NDK 17c for the AAR to load on Android 4.4
