### ISSUE TITLE
 app crashed in android 4.4

### ISSUE THREAD

**Issue by krv372** [BelledonneCommunications/linphone-sdk#8]
hi
i used liblinphone 3.15 before, i update to latest version, on android version above 6 it works well but i in android 4.4 it faild and crashed:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "random" referenced by "libbctoolbox.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:371)
at java.lang.System.loadLibrary(System.java:606)
at org.linphone.core.FactoryImpl.(Factory.java:297)
at org.linphone.core.Factory.instance(Factory.java:44)

**Comment by krv372** [comment]
i used ndk 16 to compile and it fixed
